const quotes = ["This too shall pass.",
"You are stronger than you think.",
"Embrace the journey, not just the destination.",
"Keep going, even when it's tough.",
"The darkest hour has only sixty minutes.",
"You are capable of amazing things.",
"Stars can't shine without darkness.",
"You are not alone in this battle.",
"Dream big and dare to fail.",
"Your potential is endless.",
"The best is yet to come.",
"Dreams are the currency of achievement.",
"Embrace the challenges with courage.",
"Believe in the magic of hard work.",
"Strive for excellence, not perfection.",
"Dreams are the seeds of greatness.",
"Success is a reflection of your character.",
"Your journey is your greatest teacher.",
"Don't judge, you don't know hearts.",
"Allah's guidance is the best guidance.",
"Greet with Salam (peace), spread tranquility.",
"Fear Allah in private and in public.",
"Allah's plan is better than your dreams.",
"Seek knowledge from cradle to grave.",
"Wudu (ablution): The purification of the soul.",
"Allah is the ultimate source of strength.",
"Greet with Salam (peace), spread love.",
"Kind words are a form of charity.",
"Trust Allah's plan, it's for your best.",
"Gratitude is a sign of a believer.",
"Allah's guidance is a beacon of light.",
"Pray with a heart full of gratitude.",
"Fear Allah in all your actions.",
"Allah's love is boundless and pure.",
"Repentance is the path to forgiveness.",
"Greet others with a smile and Salam.",
"Kindness is the language of the heart.",
"Allah's plan is always the wisest.",
"Every breath is a blessing from Allah.",
"Pray for guidance in every step.",
"Allah's mercy is a boundless ocean.",
"Good character is a sign of faith.",
"Gratitude attracts blessings from Allah.",
"Prayer is a conversation with Allah.",
"Trust Allah's wisdom in every trial.",
"Islam: A way of life, not just belief.",
"Allah knows what's in your heart.",
"In Allah's hands, you're in good hands.",
"Sabr (patience) is a beautiful virtue.",
"Allah's plan is always the best.",
"Trust Allah's timing and His wisdom.",
"Seek forgiveness from the Most Merciful.",
"Pray, trust, and let Allah guide.",
"Allah is the best of all planners.",
"Faith over fear, Allah is near.",
"Let your good deeds outweigh your sins.",
"Jannah (paradise): The ultimate aspiration.",
"Don't despair, Allah's mercy is limitless.",
"Every day is a chance to improve.",
"Faith in your heart, sincerity in actions.",
"Pray as if it's your last prayer.",
"Life is a test, trust the tester.",
"Good character is a mark of faith.",
"Allah's mercy covers all your sins.",
"Your purpose: To worship Allah alone.",
"Kindness is a universal language.",
"Let your actions reflect your faith.",
"Allah's love is the greatest love.",
"Hope in Allah, even in your darkest moments.",
"Trust Allah's plan, not your understanding.",
"Allah's blessings outweigh life's difficulties.",
"Be patient, Allah is with the patient.",
"Live simply, so others can simply live.",
"Islam teaches respect for all creation.",
"Gratitude is the key to abundance.",
"Don't judge, you don't know hearts.",
"Allah's guidance is the best guidance.",
"Greet with Salam (peace), spread tranquility.",
"Fear Allah in private and in public.",
"Allah's plan is better than your dreams.",
"Seek knowledge from cradle to grave.",
"Wudu (ablution): The purification of the soul.",
"Allah is the ultimate source of strength.",
"Greet with Salam (peace), spread love.",
"Kind words are a form of charity.",
"Trust Allah's plan, it's for your best.",
"Gratitude is a sign of a believer.",
"Allah's guidance is a beacon of light.",
"Pray with a heart full of gratitude.",
"Fear Allah in all your actions.",
"Allah's love is boundless and pure.",
"Repentance is the path to forgiveness.",
"Greet others with a smile and Salam.",
"Kindness is the language of the heart.",
"Allah's plan is always the wisest.",
"Every breath is a blessing from Allah.",
"Pray for guidance in every step.",
"Allah's mercy is a boundless ocean.",
"Good character is a sign of faith.",
"Gratitude attracts blessings from Allah.",
"Prayer is a conversation with Allah.",
"Trust Allah's wisdom in every trial.",
"Islam: A way of life, not just belief.",
"Allah knows what's in your heart.",
"In Allah's hands, you're in good hands.",
"Sabr (patience) is a beautiful virtue.",
"Allah's plan is always the best.",
"Trust Allah's timing and His wisdom.",
"Seek forgiveness from the Most Merciful.",
"Pray, trust, and let Allah guide.",
"Allah is the best of all planners.",
"Faith over fear, Allah is near.",
"Let your good deeds outweigh your sins.",
"Jannah (paradise): The ultimate aspiration.",
"Dreams fuel the journey of success.",
"Believe in yourself, magic happens.",
"Chase your passion, not your fears.",
"Every setback is a setup for a comeback.",
"Embrace challenges, grow through them.",
"Positivity breeds productivity.",
"Your future depends on your today.",
"Hard work beats talent when talent doesn't work hard.",
"Be fearless, be unstoppable.",
"Success is earned, not given.",
"Strive for progress, not perfection.",
"Persistence leads to excellence.",
"Keep going, don't give up.",
"You are the author of your story.",
"Doubt kills more dreams than failure.",
"Focus on the journey, not the destination.",
"The only limit is your imagination.",
"Start where you are, use what you have.",
"Opportunity dances with those already on the dance floor.",
"Small steps lead to big achievements.",
"Make today amazing!",
"Stay hungry, stay foolish.",
"Success is a state of mind.",
"Rise above the storm, find the sunshine.",
"Let your actions speak louder than words.",
"Greatness begins with a single step.",
"Failure is a stepping stone to success.",
"Create your own opportunities.",
"Stay committed to your goals.",
"Be the change you wish to see.",
"Believe. Achieve. Succeed.",
"Your time is now.",
"Every day is a fresh start.",
"Live your purpose, not your fears.",
"Success is a journey, not a destination.",
"Keep moving forward, no matter what.",
"Innovate, don't imitate.",
"Strive for greatness, settle for nothing less.",
"Stay focused, stay determined.",
"Make it happen.",
"Never stop learning.",
"The harder you work, the luckier you get.",
"Success is sweetest after struggle.",
"Dare to dream big.",
"Turn obstacles into stepping stones.",
"Stay positive, stay fighting.",
"You are stronger than you think.",
"Live with purpose, not by accident.",
"Today's actions shape tomorrow's success.",
"Your potential is limitless.",
"Choose to shine, even on cloudy days.",
"Success favors the bold.",
"Create your own sunshine.",
"Stay true to your vision.",
"Dreams don't work unless you do.",
"Be relentless in your pursuit of excellence.",
"Start small, think big.",
"The only limit is your mind.",
"Keep your eyes on the prize.",
"Don't just wish for it, work for it.",
"Believe you can, and you will.",
"Be the best version of yourself.",
"Success is the sum of small efforts.",
"Find joy in the journey.",
"Your attitude determines your altitude.",
"The harder you work, the luckier you become.",
"Every day is a chance to improve.",
"Stay positive, stay persistent.",
"Dream big, work hard, stay focused.",
"Success starts with a single step.",
"Never underestimate your potential.",
"Embrace change, embrace growth.",
"Your destiny is in your hands.",
"Make your dreams a reality.",
"Do it with passion or not at all.",
"Success is a marathon, not a sprint.",
"Keep aiming higher.",
"Every setback is a setup for a comeback.",
"Don't stop until you're proud.",
"Believe in the power of now.",
"Stay hungry for success.",
"Your future is created by what you do today.",
"Find strength in adversity.",
"Rise and grind.",
"Make every day count.",
"Hard work pays off.",
"The journey is worth it.",
"Dream, believe, achieve.",
"Stay focused on your goals.",
"Great things take time.",
"Success is a choice.",
"Stay positive, stay strong.",
"Never give up on your dreams.",
"You are capable of greatness.",
"Embrace challenges, embrace growth.",
"Dream it. Believe it. Achieve it.",
"Don't wait for opportunity, create it.",
"You are the architect of your destiny.",
"Success begins with self-discipline.",
"Keep pushing forward, no matter what.",
"Your potential is endless.",
"Determination leads to success.",
"Success requires sacrifice.",
"Be fearless in the pursuit of greatness.",
"Stay positive, stay hopeful.",
"Hard work breeds success.",
"Dreams don't expire.",
"The best is yet to come.",
"Effort fuels achievement.",
"Stay persistent, stay dedicated.",
"Success demands hustle.",
"Challenges make you stronger.",
"Believe in your abilities.",
"You are a force of nature.",
"Be the change you seek.",
"Every day is a gift.",
"Dare to be different.",
"Success is your destiny.",
"Live with purpose, not by chance.",
"Resilience conquers all.",
"Your journey matters.",
"Stay focused, stay fierce.",
"Embrace the unknown.",
"The future is what you make it.",
"Success is a mindset.",
"Stay inspired, stay motivated.",
"Dreams fuel ambition.",
"Opportunity knocks for the prepared.",
"Believe in your inner strength.",
"Strive for excellence.",
"Stay positive, stay powerful.",
"Success is a journey of a thousand steps.",
"Make your passion your paycheck.",
"Your effort defines your success.",
"Chase your dreams relentlessly.",
"Don't settle for mediocrity.",
"The harder you work, the luckier you get.",
"Success is a reflection of your actions.",
"Every moment is a fresh beginning.",
"Believe in the beauty of your dreams.",
"Your attitude shapes your reality.",
"Stay committed, stay inspired.",
"Embrace the challenges of today.",
"Success is a choice you make.",
"Rise above the noise.",
"Your journey is unique.",
"Dreams are the blueprints of success.",
"Stay hungry for achievement.",
"Work hard in silence; let success make the noise.",
"Success comes to those who persist.",
"Believe in your infinite potential.",
"You are the CEO of your life.",
"Chase your goals with determination.",
"Strive for greatness every day.",
"Stay positive, stay passionate.",
"Your dreams are your reality in the making.",
"Success is a marathon, not a sprint.",
"Every setback is a setup for a comeback.",
"Make your actions speak loudly.",
"Challenges are opportunities in disguise.",
"Dreams are the building blocks of success.",
"Stay determined, stay focused.",
"Success requires relentless effort.",
"Embrace your unique journey.",
"Believe in the power within you.",
"Your potential knows no limits.",
"Stay driven, stay inspired.",
"Hard work paves the path to success.",
"Your goals are your compass.",
"Success is the sum of small efforts.",
"Stay positive, stay relentless.",
"Dream big and dare to fail.",
"Rise above the challenges.",
"Your actions define your destiny.",
"Success is a reflection of your choices.",
"Stay motivated, stay unstoppable.",
"Believe in your ability to overcome.",
"Strive for excellence in everything.",
"Dreams are the fuel of ambition.",
"Success is a journey, not a destination.",
"Embrace the power of now.",
"Your journey is your legacy.",
"Believe in the process of growth.",
"Stay hungry, stay humble.",
"Success is the result of persistence.",
"Your dreams are worth the effort.",
"Stay positive, stay resilient.",
"Seek forgiveness from the Most Merciful.",
"Allah's plan is always the best.",
"Trust Allah's timing and His wisdom.",
"Pray, trust, and let Allah guide.",
"Start with Bismillah, end with Alhamdulillah.",
"Sabr (patience) is a beautiful virtue.",
"Allah is the best of all planners.",
"Islam: A way of life, not just faith.",
"Gratitude is the key to contentment.",
"Allah knows what's best for you.",
"Prayer is the key to inner peace.",
"Stay humble, Allah sees your heart.",
"Trust Allah, even when you don't understand.",
"Every hardship has ease, trust Allah.",
"Faith over fear, Allah is near.",
"Keep your heart clean and sincere.",
"Allah's mercy is greater than our sins.",
"Repentance: A door to Allah's forgiveness.",
"Allah's love is greater than your mistakes.",
"Pray and find solace in sujood.",
"Dua (supplication): Your direct line to Allah.",
"Have faith, Allah is in control.",
"Quran: A guide for all of humanity.",
"Actions speak louder than words, Islamically.",
"Modesty is a crown for the believer.",
"Jannah (paradise): The ultimate aspiration.",
"Let your good deeds outweigh your sins.",
"In Allah's hands, you're in good hands.",
"Trust Allah's plan, it's always perfect.",
"Forgive others, Allah will forgive you.",
"Don't despair, Allah's mercy is limitless.",
"Every day is a chance to improve.",
"Faith in your heart, sincerity in actions.",
"Pray as if it's your last prayer.",
"Life is a test, trust the tester.",
"Good character is a mark of faith.",
"Allah's mercy covers all your sins.",
"Your purpose: To worship Allah alone.",
"Kindness is a universal language.",
"Let your actions reflect your faith.",
"Allah's love is the greatest love.",
"Hope in Allah, even in your darkest moments.",
"Trust Allah's plan, not your understanding.",
"Allah's blessings outweigh life's difficulties.",
"Be patient, Allah is with the patient.",
"Live simply, so others can simply live.",
"Islam teaches respect for all creation.",
"Gratitude is the key to abundance.",
"Don't judge, you don't know hearts.",
"Allah's guidance is the best guidance.",
"Be kind to others, it's Sunnah (tradition).",
"Hearts find peace in remembering Allah.",
"Turn to Allah when your heart aches.",
"Allah's plan is better than your dreams.",
"Seek knowledge from cradle to grave.",
"Wudu (ablution): The purification of the soul.",
"Allah is the ultimate source of strength.",
"Greet with Salam (peace), spread tranquility.",
"Fear Allah in private and in public.",
"Allah's mercy is greater than any sin.",
"Be a seeker of knowledge always.",
"The Quran is a healing for hearts.",
"Pray for the living and the deceased.",
"Your sincerity is your most precious possession.",
"Make dua, it's a weapon for the believer.",
"Forgive, as Allah forgives your sins.",
"Allah's timing is perfect, trust it.",
"A smile is charity in Islam.",
"Gratitude attracts more blessings from Allah.",
"The Quran is your roadmap in life.",
"Be grateful, Allah loves the thankful.",
"Start with Bismillah, end with Alhamdulillah.",
"Kindness to animals is rewarded by Allah.",
"Turn to Allah in times of distress.",
"Allah's plan is the best plan.",
"Patience is the key to paradise.",
"Allah's mercy encompasses everything.",
"Trust Allah's wisdom in all matters.",
"Allah's love is constant and unwavering.",
"In Allah's remembrance, hearts find peace.",
"The Quran is the light of guidance.",
"Repentance is a path to Allah's mercy.",
"Kindness to parents is a duty.",
"Life's difficulties are tests from Allah.",
"Allah's blessings are too numerous to count.",
"Gratitude is the sign of a believer.",
"Prayer is your connection to Allah.",
"Sincerity is the essence of worship.",
"The Quran is a book of guidance.",
"Trust in Allah's plan, it's perfect.",
"Allah's mercy is greater than your sins.",
"Repentance: A door to Allah's forgiveness.",
"Allah knows what's in your heart.",
"Prayer is the key to inner peace.",
"In Allah's hands, you're in good hands.",
"Sabr (patience) is a beautiful virtue.",
"Allah's plan is always the best.",
"Trust Allah's timing and His wisdom.",
"Seek forgiveness from the Most Merciful.",
"Pray, trust, and let Allah guide.",
"Islam: A way of life, not just faith.",
"Gratitude is the key to contentment.",
"Allah is the best of all planners.",
"Faith over fear, Allah is near.",
"Let your good deeds outweigh your sins.",
"Jannah (paradise): The ultimate aspiration.",
"Don't despair, Allah's mercy is limitless.",
"Every day is a chance to improve.",
"Faith in your heart, sincerity in actions.",
"Pray as if it's your last prayer.",
"Life is a test, trust the tester.",
"Good character is a mark of faith.",
"Allah's mercy covers all your sins.",
"Your purpose: To worship Allah alone.",
"Kindness is a universal language.",
"Let your actions reflect your faith.",
"Allah's love is the greatest love.",
"Hope in Allah, even in your darkest moments.",
"Trust Allah's plan, not your understanding.",
"Allah's blessings outweigh life's difficulties.",
"Be patient, Allah is with the patient.",
"Live simply, so others can simply live.",
"Islam teaches respect for all creation.",
"Gratitude is the key to abundance.",
];

const getQuote = ()=>{
    return quotes[Math.floor(Math.random() * quotes.length)];
} 

const quoteText = document.querySelector(".quote");
const quoteBtn = document.querySelector("button");
const copyBtn = document.querySelector(".copy");



quoteBtn.addEventListener("click",()=>{
    const quote = getQuote();
    quoteText.innerText = quote;
    copyBtn.style.display = "inline-block"
    quoteBtn.innerText = "New Quote"
})

copyBtn.addEventListener("click", () => {
  navigator.clipboard.writeText(quoteText.innerText);
});